name: Deploy WebApp   
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
  push:
    branches: [master]   

jobs:
  sast_scan:
    uses: ./.github/workflows/sast_scan.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-heroku:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    needs: sast_scan
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "leonardo-battistelli-devsecops" 
          heroku_email: "leonardo.baty@gmail.com"
          remote_branch: "master"
          usedocker: true
  
  zap_scan:
    name: Scan the webapplication
    runs-on: ubuntu-latest    
    needs: deploy-heroku
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.DAST_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://leonardo-battistelli-devsecops.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
