name: docker
on: 
  push:
    branches:
      - master
  pull_request:
    branches: [master]
  
jobs:
  trivy:
    name: trivy    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      

  anchore:
    name: anchore_scan
    runs-on: ubuntu-latest
    needs: trivy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Build 
        run: |
          docker build -t anchore-image:${{ github.sha }} .

      - name: anchore_scan
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: anchore-image:${{ github.sha }}
          severity-cutoff: high
          acs-report-enable: true          

      - name: Upload SARIF File
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}