name: Nuclei - DAST Scan

on:
  push:

jobs:
  nuclei-scan:
    name: nuclei-scan2
    runs-on: ubuntu-latest    
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://leonardo-battistelli-devsecops.herokuapp.com/
          flags: "-severity critical,high -stats"
          github-report: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: GitHub Workflow artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: nuclei.log
      #     path: nuclei.log

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuclei.log
          path: nuclei.log


      # - name: GitHub Security Dashboard Alerts
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: nuclei.sarif