name: synk_scan
on: 
  push:
    branches:
      - master
  pull_request:
    branches: [master]
jobs: 
  snyk_scan_code:
    name: Snyk Code
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with: 
          args: >                 
            --sarif-file-output=synkscan.sarif
      - name: Upload SARIF File as json
        uses: actions/upload-artifact@v3
        with:
          name: synkscan
          path: synkscan-config.json

  snyk_docker:
    name: snyk_docker
    runs-on: ubuntu-latest
    #needs: snyk_scan_code
    permissions:
      # required for all workflows
      security-events: write
    steps:
      ## Checkout is required since Snyk needs the Dockerfile for the Sarif report
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Docker Build
        run: |
          docker build -t image-snyk:${{ github.sha }} . 
      - name: Snyk
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: image-snyk:${{ github.sha }}
          args: >
            --file=Dockerfile
            --severity-threshold=high
      - name: Upload SARIF File as json
        uses: actions/upload-artifact@v3
        with:
          name: snyk_docker
          path: synkscan-docker-config.json