name: synk_scan
on: 
  push:
    branches:
      - master
  pull_request:
    branches: [master]
jobs: 
  snyk_scan_code:
    name: Snyk Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: >
            --severity-threshold=high
            --all-projects
            --sarif-file-output=snyk-code.sarif
      - name: Upload SARIF file
        #if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif  

  snyk_docker:
    name: snyk_docker
    runs-on: ubuntu-latest
    needs: snyk_scan_code
    steps:
      ## Checkout is required since Snyk needs the Dockerfile for the Sarif report
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Docker Build
        run: |
          docker build -t image-snyk:${{ github.sha }} . 
      - name: Snyk
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: image-snyk:${{ github.sha }}
          args: >
            --file=Dockerfile
            --severity-threshold=high
      - name: Upload SARIF file        
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif